#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine
# Install nginx  web server and returns page containing a string

# update dependecies & install nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

#starts ngix web server
sudo service nginx start

string_file=/var/www/html/index.nginx-debian.html

sudo bash -c "echo 'Hello World!' > $string file"
