#!/usr/bin/env bash
# Installs and configures HAProxy in a load balancer server

# Install prerequisites
sudo apt-get install -y software-properties-common

# Add HAProxy PPA (version 2.0)
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy in /etc/default/haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Backup the original HAProxy configuration file and create a new one
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

# Append HAProxy configuration to /etc/haproxy/haproxy.cfg
printf %s "global
log 127.0.0.1 local0 notice
maxconn 2000
user haproxy
group haproxy
defaults
log     global
mode    http
option  httplog
option  dontlognull
retries 3
option redispatc
timeout connect  500
timeout client  10000
timeout server  10000
listen hbnb
bind 0.0.0.0:80
mode http
stats enable
stats uri /haproxy?stats
balance roundrobin
option httpclose
option forwardfor
server 188045-web1 52.91.152.199:80 check
server 188045-web2 54.90.22.62:80 check
"| sudo tee -a /etc/haproxy/haproxy.cfg

# Start the HAProxy service
sudo service haproxy start
